version: 2.1
jobs:
  build:
    machine: true
    environment:
      version: "0.1"
    steps:
      - checkout
      - run:
          name: Login to hub.docker.com
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Run docker build
          command: docker build -t jayamorin/kube-utils:latest .
      - run:
          name: Tag docker build
          command: |
            docker tag jayamorin/kube-utils:latest jayamorin/kube-utils:$version.$CIRCLE_SHA1
      - run:
          name: Push docker build to hub.docker.com
          command: |
            docker push jayamorin/kube-utils:$version.$CIRCLE_SHA1
            docker push jayamorin/kube-utils:latest

workflows:
  version: 2
  kube-utils:
    jobs:
      - build:
          filters:
            branches:
              only: master